// svelte-app/src/components/ListHeader.svelte
<script lang="ts">
  import { Link } from 'svelte-routing';
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();
  export let title = '';
  export let routePath = '';
</script>

<div class="content-title-group">
  <Link to={routePath}>
    <h2 class="title">{title}</h2>
  </Link>
  <button
    class="button refresh-button"
    on:click={() => dispatch('refresh')}
    aria-label="refresh">
    <i class="fas fa-sync" aria-hidden="true" />
  </button>
</div>

// react-app/src/components/ListHeader.js
import React from 'react';
import { NavLink } from 'react-router-dom';

const ListHeader = ({ title, handleRefresh, routePath }) => {
  return (
    <div className="content-title-group">
      <NavLink to={routePath}>
        <h2 className="title">{title}</h2>
      </NavLink>
      <button
        className="button refresh-button"
        onClick={handleRefresh}
        aria-label="refresh"
      >
        <i className="fas fa-sync" aria-hidden="true" />
      </button>
    </div>
  );
};

export default ListHeader;
