// svelte-app/src/components/HeaderBarBrand.svelte
<div class="navbar-brand">
  <a
    class="navbar-item"
    href="https://svelte.dev/"
    target="_blank"
    rel="noopener noreferrer">
    <img src="./svelte-icon.png" alt="Svelte" />
  </a>
  <router-link to="/" class="navbar-item nav-home">
    <span class="brand-first">VACATION</span>
    <span class="brand-second">WISH</span>
    <span class="brand-third">LIST</span>
  </router-link>
</div>

// vue-app/src/components/header-bar-brand.vue
<script>
export default {
  name: 'HeaderBarBrand',
};
</script>

<template>
  <div class="navbar-brand">
    <a
      class="navbar-item"
      href="https://vuejs.org/"
      target="_blank"
      rel="noopener noreferrer"
    >
      <i class="fab js-logo fa-vuejs fa-2x" aria-hidden="true" />
    </a>
    <router-link to="/" class="navbar-item nav-home">
      <span class="brand-first">VACATION</span>
      <span class="brand-second">WISH</span>
      <span class="brand-third">LIST</span>
    </router-link>
  </div>
</template>
