// vue-app/src/app.vue
<script>
import HeaderBar from '@/components/header-bar.vue';
import NavBar from '@/components/nav-bar.vue';

export default {
  name: 'App',
  data() {
    return {};
  },
  components: {
    HeaderBar,
    NavBar,
  },
};
</script>

<template>
  <div id="app">
    <HeaderBar />
    <div class="section columns">
      <NavBar />
      <main class="column">
        <router-view />
      </main>
    </div>
  </div>
</template>

<style lang="scss">
@use 'styles.scss';
</style>

// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
export class Customer {
  public id: number;
  public name: string;
}
@Component({
  selector: 'app-root',
  styleUrls: ['./app.component.scss'],
  template: `
    <div>
      <app-header-bar></app-header-bar>
      <div class="section columns">
        <app-nav class="column is-2"></app-nav>
        <main class="column">
          <router-outlet></router-outlet>
        </main>
      </div>
    </div>
  `,

})
export class AppComponent {
  customers: Customer[] = [{ id: 1, name: 'john' }];
}
