// svelte-app/src/products/Products.svelte
<script>
  import { onMount } from 'svelte';
  import { ListHeader } from '../components';
  import ProductList from './ProductList.svelte';
  import { state, getProductsAction } from '../store';

  const { products } = state;

  let routePath = '/products';
  let title = 'Products';

  onMount(async () => await getProducts());

  async function getProducts() {
    await getProductsAction();
  }
</script>

<div class="content-container">
  <ListHeader {title} {routePath} on:refresh={getProducts} />
  <div class="columns is-multiline is-variable">
    {#if products}
      <div class="column is-8">
        <ProductList products={$products} />
      </div>
    {/if}
  </div>

</div>

// react-app/src/products/Products.js
import React, { useEffect } from 'react';
import { Route, Routes } from 'react-router-dom';

import { ListHeader } from '../components';
import ProductList from './ProductList';
import useProducts from './useProducts';

function Products() {
  const { getProducts, products } = useProducts();

  useEffect(() => {
    getProducts();
  }, [getProducts]);

  function handleRefresh() {
    getProducts();
  }

  return (
    <div className="content-container">
      <ListHeader
        title="Products"
        handleRefresh={handleRefresh}
        routePath="/products"
      />
      <div className="columns is-multiline is-variable">
        <div className="column is-8">
          <Routes>
            <Route
              path="/*"
              element={<ProductList products={products} />}
            />
          </Routes>
        </div>
      </div>
    </div>
  );
}

export default Products;
