// svelte-app/src/vacations/Vacations.svelte
<script>
  import { onMount } from 'svelte';
  import { ListHeader, Modal } from '../components';
  import VacationList from './VacationList.svelte';
  import VacationDetail from './VacationDetail.svelte';
  import {
    state,
    getVacationsAction,
    deleteVacationAction,
    addVacationAction,
    updateVacationAction
  } from '../store';

  const { vacations } = state;

  let selected = undefined;
  let routePath = '/vacations';
  let title = 'Vacations';
  let vacationToDelete = null;
  let message = '';
  let showModal = false;

  onMount(async () => await getVacations());

  function enableAddMode() {
    selected = {};
  }

  function askToDelete({ detail: vacation }) {
    vacationToDelete = vacation;
    showModal = true;
    if (vacationToDelete.name) {
      message = `Would you like to delete ${vacationToDelete.name}?`;
    }
  }

  function clear() {
    selected = null;
  }

  function closeModal() {
    showModal = false;
  }

  async function deleteVacation() {
    closeModal();
    if (vacationToDelete) {
      console.log(`You said you want to delete ${vacationToDelete.name}`);
      await deleteVacationAction(vacationToDelete);
    }
    clear();
  }

  async function getVacations() {
    await getVacationsAction();
  }

  async function save({ detail: vacation }) {
    console.log('vacation changed', vacation);
    if (vacation.id) {
      await updateVacationAction(vacation);
    } else {
      await addVacationAction(vacation);
    }
  }

  function select({ detail: vacation }) {
    selected = vacation;
    console.log(`selected ${vacation.name}`);
  }
</script>

<div class="content-container">
  <ListHeader
    {title}
    {routePath}
    on:add={enableAddMode}
    on:refresh={getVacations} />
  <div class="columns is-multiline is-variable">
    {#if vacations}
      <div class="column is-8">
        {#if !selected}
          <VacationList
            vacations={$vacations}
            on:deleted={askToDelete}
            on:selected={select} />
        {:else}
          <VacationDetail
            vacation={selected}
            on:unselect={clear}
            on:save={save} />
        {/if}
      </div>
    {/if}
  </div>

  <Modal
    {message}
    isOpen={showModal}
    on:handleNo={closeModal}
    on:handleYes={deleteVacation} />
</div>

// react-app/src/vacations/Vacations.js
import React, { useEffect, useState } from 'react';
import { Route, Switch } from 'react-router-dom';

import { ListHeader, ModalYesNo } from '../components';
import VacationDetail from './VacationDetail';
import VacationList from './VacationList';
import useVacations from './useVacations';

const captains = console;

function Vacations({ history }) {
  const [vacationToDelete, setVacationToDelete] = useState(null);
  const [showModal, setShowModal] = useState(false);
  const {
    addVacation,
    deleteVacation,
    getVacations,
    vacations,
    selectVacation,
    selectedVacation,
    updateVacation,
  } = useVacations();

  useEffect(() => {
    getVacations();
  }, [getVacations]);

  function addNewVacation() {
    selectVacation({});
    history.push('/vacations/0');
  }

  function handleCancelVacation() {
    history.push('/vacations');
    selectVacation(null);
    setVacationToDelete(null);
  }

  function handleDeleteVacation(vacation) {
    selectVacation(null);
    setVacationToDelete(vacation);
    setShowModal(true);
  }

  function handleSaveVacation(vacation) {
    if (selectedVacation && selectedVacation.name) {
      captains.log(vacation);
      updateVacation(vacation);
    } else {
      addVacation(vacation);
    }
    handleCancelVacation();
  }

  function handleCloseModal() {
    setShowModal(false);
  }

  function handleDeleteFromModal() {
    setShowModal(false);
    deleteVacation(vacationToDelete);
    handleCancelVacation();
  }

  function handleSelectVacation(selectedVacation) {
    selectVacation(selectedVacation);
    captains.log(`you selected ${selectedVacation.name}`);
  }

  function handleRefresh() {
    handleCancelVacation();
    getVacations();
  }

  return (
    <div className="content-container">
      <ListHeader
        title="Vacations"
        handleAdd={addNewVacation}
        handleRefresh={handleRefresh}
        routePath="/vacations"
      />
      <div className="columns is-multiline is-variable">
        <div className="column is-8">
          <Switch>
            <Route
              exact
              path="/vacations"
              component={() => (
                <VacationList
                  vacations={vacations}
                  selectedVacation={selectedVacation}
                  handleSelectVacation={handleSelectVacation}
                  handleDeleteVacation={handleDeleteVacation}
                />
              )}
            />
            <Route
              exact
              path="/vacations/:id"
              component={() => {
                return (
                  <VacationDetail
                    vacation={selectedVacation}
                    handleCancelVacation={handleCancelVacation}
                    handleSaveVacation={handleSaveVacation}
                  />
                );
              }}
            />
          </Switch>
        </div>
      </div>

      {showModal && (
        <ModalYesNo
          message={`Would you like to delete ${vacationToDelete.name}?`}
          onNo={handleCloseModal}
          onYes={handleDeleteFromModal}
        />
      )}
    </div>
  );
}

export default Vacations;
