// react-app/src/vacations/VacationList.js
import React from 'react';
import { withRouter } from 'react-router';

import { ButtonFooter, CardContent } from '../components';

function VacationList({
  handleDeleteVacation,
  handleSelectVacation,
  vacations,
  history,
}) {
  function selectVacation(e) {
    const vacation = getSelectedVacation(e);
    handleSelectVacation(vacation);
    history.push(`/vacations/${vacation.id}`);
  }

  function deleteVacation(e) {
    const vacation = getSelectedVacation(e);
    handleDeleteVacation(vacation);
  }

  function getSelectedVacation(e) {
    const index = +e.currentTarget.dataset.index;
    return vacations[index];
  }

  return (
    <ul className="list">
      {vacations.map((vacation, index) => (
        <li key={vacation.id} role="presentation">
          <div className="card">
            <CardContent
              name={vacation.name}
              description={vacation.description}
            />
            <footer className="card-footer">
              <ButtonFooter
                className="delete-item"
                iconClasses="fas fa-trash"
                onClick={deleteVacation}
                label="Delete"
                dataIndex={index}
                dataId={vacation.id}
              />
              <ButtonFooter
                className="edit-item"
                iconClasses="fas fa-edit"
                onClick={selectVacation}
                label="Edit"
                dataIndex={index}
                dataId={vacation.id}
              />
            </footer>
          </div>
        </li>
      ))}
    </ul>
  );
}

export default withRouter(VacationList);

// svelte-app/src/vacations/VacationList.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import { ButtonFooter, CardContent } from '../components';

  const dispatch = createEventDispatcher();
  export let vacations = [];

  function deleteVacation(vacation) {
    dispatch('deleted', vacation);
  }

  function selectVacation(vacation) {
    dispatch('selected', vacation);
  }

  const deleteOptions = {
    className: 'delete-item',
    label: 'Delete',
    iconClasses: 'fas fa-trash'
  };

  const editOptions = {
    className: 'edit-item',
    label: 'Edit',
    iconClasses: 'fas fa-edit'
  };
</script>

<ul class="list">
  {#each vacations as { id, name, description }, i (id)}
    <li role="presentation">
      <div class="card">
        <CardContent {name} {description} />
        <footer class="card-footer">
          <ButtonFooter
            {...deleteOptions}
            dataId={id}
            dataIndex={i}
            item={vacations[i]}
            on:clicked={deleteVacation(vacations[i])} />
          <ButtonFooter
            {...editOptions}
            dataId={id}
            dataIndex={i}
            item={vacations[i]}
            on:clicked={selectVacation(vacations[i])} />
        </footer>
      </div>
    </li>
  {/each}
</ul>
