// react-app/src/vacations/VacationDetail.js
import React, { useEffect, useState } from 'react';
import { withRouter } from 'react-router';

import { ButtonFooter, InputDetail } from '../components';

function VacationDetail({
  vacation: initVacation,
  handleCancelVacation,
  handleSaveVacation,
  history,
}) {
  const [vacation, setVacation] = useState(Object.assign({}, initVacation));

  useEffect(() => {
    if (!vacation) {
      history.push('/vacations'); // no vacation, bail out of Details
    }
  }, [vacation, history]);

  function handleSave() {
    const chgVacation = { ...vacation, id: vacation.id || null };
    handleSaveVacation(chgVacation);
  }

  function handleNameChange(e) {
    setVacation({ ...vacation, name: e.target.value });
  }

  function handleDescriptionChange(e) {
    setVacation({ ...vacation, description: e.target.value });
  }

  return (
    <div className="card edit-detail">
      <header className="card-header">
        <p className="card-header-title">
          {vacation.name}
          &nbsp;
        </p>
      </header>
      <div className="card-content">
        <div className="content">
          {vacation.id && (
            <InputDetail name="id" value={vacation.id} readOnly="true" />
          )}
          <InputDetail
            name="name"
            value={vacation.name}
            placeholder="e.g Colleen"
            onChange={handleNameChange}
          />
          <InputDetail
            name="description"
            value={vacation.description}
            placeholder="e.g dance fight!"
            onChange={handleDescriptionChange}
          />
        </div>
      </div>
      <footer className="card-footer ">
        <ButtonFooter
          className="cancel-button"
          iconClasses="fas fa-undo"
          onClick={handleCancelVacation}
          label="Cancel"
        />
        <ButtonFooter
          className="save-button"
          iconClasses="fas fa-save"
          onClick={handleSave}
          label="Save"
        />
      </footer>
    </div>
  );
}

export default withRouter(VacationDetail);

// vue-app/src/views/vacations/vacation-detail.vue
<script>
import ButtonFooter from '@/components/button-footer.vue';

export default {
  name: 'VacationDetail',
  props: {
    vacation: {
      type: Object,
      default() {},
    },
  },
  components: { ButtonFooter },
  data() {
    return {
      addMode: false,
      editingVacation: { ...this.vacation },
    };
  },
  watch: {
    vacation() {
      if (this.vacation && this.vacation.id) {
        this.editingVacation = { ...this.vacation };
        this.addMode = false;
      } else {
        this.editingVacation = { id: undefined, name: '', description: '' };
        this.addMode = true;
      }
    },
  },
  methods: {
    clear() {
      this.$emit('unselect');
    },
    saveVacation() {
      this.$emit('save', this.editingVacation);
      this.clear();
    },
  },
};
</script>

<template>
  <div class="card edit-detail">
    <header class="card-header">
      <p class="card-header-title">{{ editingVacation.name }}</p>
    </header>
    <div class="card-content">
      <div class="content">
        <div class="field" v-if="editingVacation.id">
          <label class="label" for="id">id</label>
          <input
            class="input"
            name="id"
            placeholder="e.g. VacationColleen"
            readonly
            type="text"
            v-model="editingVacation.id"
          />
        </div>
        <div class="field">
          <label class="label" for="name">name</label>
          <input
            class="input"
            name="name"
            placeholder="e.g. Colleen"
            type="text"
            v-model="editingVacation.name"
          />
        </div>
        <div class="field">
          <label class="label" for="description">description</label>
          <input
            class="input"
            name="description"
            placeholder="dance fight!"
            type="text"
            v-model="editingVacation.description"
          />
        </div>
      </div>
    </div>
    <footer class="card-footer">
      <ButtonFooter
        class="card-footer-item"
        label="Cancel"
        :className="'cancel-button'"
        :iconClasses="'fas fa-undo'"
        :item="editingVacation"
        @clicked="clear"
      ></ButtonFooter>
      <ButtonFooter
        class="card-footer-item"
        :className="'save-button'"
        :iconClasses="'fas fa-save'"
        :item="editingVacation"
        label="Save"
        @clicked="saveVacation"
      ></ButtonFooter>
    </footer>
  </div>
</template>
