// svelte-app/src/vacations/Vacations.svelte
<script>
  import { onMount } from 'svelte';
  import { ListHeader, Modal } from '../components';
  import VacationList from './VacationList.svelte';
  import VacationDetail from './VacationDetail.svelte';
  import {
    state,
    getVacationsAction,
    deleteVacationAction,
    addVacationAction,
    updateVacationAction
  } from '../store';

  const { vacations } = state;

  let selected = undefined;
  let routePath = '/vacations';
  let title = 'Vacations';
  let vacationToDelete = null;
  let message = '';
  let showModal = false;

  onMount(async () => await getVacations());

  function enableAddMode() {
    selected = {};
  }

  function askToDelete({ detail: vacation }) {
    vacationToDelete = vacation;
    showModal = true;
    if (vacationToDelete.name) {
      message = `Would you like to delete ${vacationToDelete.name}?`;
    }
  }

  function clear() {
    selected = null;
  }

  function closeModal() {
    showModal = false;
  }

  async function deleteVacation() {
    closeModal();
    if (vacationToDelete) {
      console.log(`You said you want to delete ${vacationToDelete.name}`);
      await deleteVacationAction(vacationToDelete);
    }
    clear();
  }

  async function getVacations() {
    await getVacationsAction();
  }

  async function save({ detail: vacation }) {
    console.log('vacation changed', vacation);
    if (vacation.id) {
      await updateVacationAction(vacation);
    } else {
      await addVacationAction(vacation);
    }
  }

  function select({ detail: vacation }) {
    selected = vacation;
    console.log(`selected ${vacation.name}`);
  }
</script>

<div class="content-container">
  <ListHeader
    {title}
    {routePath}
    on:add={enableAddMode}
    on:refresh={getVacations} />
  <div class="columns is-multiline is-variable">
    {#if vacations}
      <div class="column is-8">
        {#if !selected}
          <VacationList
            vacations={$vacations}
            on:deleted={askToDelete}
            on:selected={select} />
        {:else}
          <VacationDetail
            vacation={selected}
            on:unselect={clear}
            on:save={save} />
        {/if}
      </div>
    {/if}
  </div>

  <Modal
    {message}
    isOpen={showModal}
    on:handleNo={closeModal}
    on:handleYes={deleteVacation} />
</div>

// vue-app/src/views/vacations/vacations.vue
<script>
import { mapActions, mapGetters } from 'vuex';
import ListHeader from '@/components/list-header.vue';
import Modal from '@/components/modal.vue';
import VacationDetail from './vacation-detail.vue';
import VacationList from './vacation-list.vue';

const captains = console;

export default {
  name: 'Vacations',
  data() {
    return {
      vacationToDelete: null,
      message: '',
      routePath: '/vacations',
      selected: null,
      showModal: false,
      title: 'Vacations',
    };
  },
  components: {
    ListHeader,
    VacationList,
    VacationDetail,
    Modal,
  },
  created() {
    this.getVacationsAction();
  },
  computed: {
    ...mapGetters('vacations', { vacations: 'vacations' }),
  },
  methods: {
    ...mapActions('vacations', [
      'getVacationsAction',
      'deleteVacationAction',
      'addVacationAction',
      'updateVacationAction',
    ]),
    askToDelete(vacation) {
      this.vacationToDelete = vacation;
      this.showModal = true;
      if (this.vacationToDelete.name) {
        this.message = `Would you like to delete ${this.vacationToDelete.name}?`;
        captains.log(this.message);
      }
    },
    clear() {
      this.selected = null;
    },
    closeModal() {
      this.showModal = false;
    },
    deleteVacation() {
      this.closeModal();
      if (this.vacationToDelete) {
        captains.log(
          `You said you want to delete ${this.vacationToDelete.name}`
        );
        this.deleteVacationAction(this.vacationToDelete);
      }
      this.clear();
    },
    enableAddMode() {
      this.selected = {};
    },
    getVacations() {
      this.getVacationsAction();
      this.clear();
    },
    save(vacation) {
      captains.log('vacation changed', vacation);
      if (vacation.id) {
        this.updateVacationAction(vacation);
      } else {
        this.addVacationAction(vacation);
      }
    },
    select(vacation) {
      this.selected = vacation;
    },
  },
};
</script>

<template>
  <div class="content-container">
    <ListHeader
      :title="title"
      @refresh="getVacations"
      @add="enableAddMode"
      :routePath="routePath"
    ></ListHeader>
    <div class="columns is-multiline is-variable">
      <div class="column is-8" v-if="vacations">
        <VacationList
          v-if="!selected"
          :vacations="vacations"
          @selected="select($event)"
          @deleted="askToDelete($event)"
        ></VacationList>
        <VacationDetail
          v-if="selected"
          :vacation="selected"
          @unselect="clear"
          @save="save"
        ></VacationDetail>
      </div>
    </div>

    <Modal
      class="modal-vacation"
      :message="message"
      :isOpen="showModal"
      @handleNo="closeModal"
      @handleYes="deleteVacation"
    ></Modal>
  </div>
</template>
