// vue-app/src/components/button-footer.vue
<script>
export default {
  name: 'ButtonFooter',
  emits: ['clicked'],
  props: {
    item: {
      type: Object,
      default() {},
    },
    className: {
      type: String,
      default: () => '',
    },
    label: {
      type: String,
      default: () => '',
    },
    dataIndex: {
      type: Number,
      default: () => null,
    },
    dataId: {
      type: Number,
    },
    iconClasses: {
      type: String,
      default: () => '',
    },
  },
  methods: {
    handleClick() {
      this.$emit('clicked', this.item);
    },
  },
};
</script>

<template>
  <button
    class="link card-footer-item"
    :class="className"
    :aria-label="label"
    tabindex="0"
    @click="handleClick"
    :data-index="dataIndex"
    :data-id="dataId"
  >
    <i :class="iconClasses"></i>
    <span>{{ label }}</span>
  </button>
</template>

// svelte-app/src/components/ButtonFooter.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();

  export let item = undefined;
  export let className = '';
  export let label = '';
  export let dataIndex = 0;
  export let dataId = '';
  export let iconClasses = '';

  function handleClick() {
    console.log(`button clicked ${JSON.stringify(item)}`);
    dispatch('clicked', item);
  }
</script>

<button
  class="link card-footer-item {className}"
  aria-label={label}
  tabindex="0"
  on:click={handleClick}
  data-index={dataIndex}
  data-id={dataId}>
  <i class={iconClasses} />
  <span>{label}</span>
</button>
