// vue-app/src/views/products/products.vue
<script>
import { mapActions, mapGetters } from 'vuex';
import ListHeader from '@/components/list-header.vue';
import ProductList from './product-list.vue';

export default {
  name: 'Products',
  data() {
    return {
      routePath: '/products',
      title: 'Products',
    };
  },
  components: {
    ListHeader,
    ProductList,
  },
  created() {
    this.getProductsAction();
  },
  computed: {
    ...mapGetters('products', { products: 'products' }),
  },
  methods: {
    ...mapActions('products', ['getProductsAction']),
    getProducts() {
      this.getProductsAction();
    },
  },
};
</script>

<template>
  <div class="content-container">
    <ListHeader
      :title="title"
      @refresh="getProducts"
      :routePath="routePath"
    ></ListHeader>
    <div class="columns is-multiline is-variable">
      <div class="column is-8" v-if="products">
        <ProductList :products="products"></ProductList>
      </div>
    </div>
  </div>
</template>

// svelte-app/src/products/Products.svelte
<script>
  import { onMount } from 'svelte';
  import { ListHeader } from '../components';
  import ProductList from './ProductList.svelte';
  import { state, getProductsAction } from '../store';

  const { products } = state;

  let routePath = '/products';
  let title = 'Products';

  onMount(async () => await getProducts());

  async function getProducts() {
    await getProductsAction();
  }
</script>

<div class="content-container">
  <ListHeader {title} {routePath} on:refresh={getProducts} />
  <div class="columns is-multiline is-variable">
    {#if products}
      <div class="column is-8">
        <ProductList products={$products} />
      </div>
    {/if}
  </div>

</div>
